config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'opinions#index'
  resources :opinions, only: [:index, :new, :create, :show] do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    collection do
      get 'how_to'
    end
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  has_many :comments
  has_many :likes
  belongs_to :user
  has_one_attached :image

  validates :title, presence: {message: "can't be blank"}
  validates :text, presence: {message: "can't be blank"}, unless: :was_attached?
  validates :user, presence: {message: "can't be blank"}

  def was_attached?
    self.image.attached?
  end

  def self.search(search)
    if search != ""
      Opinion.where('text LIKE(?) OR title LIKE(?)', "%#{search}%", "%#{search}%").order("created_at DESC")
    else
      Opinion.includes(:user).order("created_at DESC")
    end
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :how_to]
  def index
    @opinions = Opinion.includes(:user).order("created_at DESC")
  end
  def new
    @opinion = Opinion.new
  end

  def create
    @opinion = Opinion.new(set_opinion)
    if @opinion.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @opinion = Opinion.find(params[:id])
    @comment = Comment.new
    @comments = @opinion.comments.includes(:user)
  end

  def search
    @opinions = Opinion.search(params[:keyword])
  end

  def how_to
  end

  private
    def set_opinion
      params.require(:opinion).permit(:title, :text, :image).merge(user_id: current_user.id)
    end
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/views/opinions/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4 d-flex justify-content-center">
    <div class="container">
      <a class="navbar-brand" href="/">Mynion</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%=  link_to new_opinion_path ,class: 'nav-link text-dark' do %>
              <i class="fas fa-book-open"></i> 新規投稿
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
          <% unless current_page?(search_opinions_path) %>
          <li>
            <%=  link_to search_opinions_path, class: 'nav-link text-dark' do %>
              <%= image_tag 'ed2fe438699a3e428a7dc95d71dfee2c.png', width: 40, height: 25 %>
            <% end %>
          </li>
          <% end %>
        <% else %>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-dark' do %>
              <i class="fas fa-user-plus"></i> 新規ユーザー登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-dark' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        <% unless current_page?(how_to_opinions_path) %>
        <li>
          <%= link_to how_to_opinions_path, class: 'nav-link text-dark' do %>
            <i class="fas fa-sign-out-alt"></i> アプリの使い方
          <% end %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/opinions/how_to.html.erb
<%= render partial: "header" %>
<div class="d-flex justify-content-center align-items-center" style="margin-bottom: 30px;">
  <div>
    <h1>アプリの使い方</h1>
  </div>
</div>
<div class="container d-flex justify-content-center align-items-center">
  <div class="container">
    <div class="card" style="width: 80vw; height: 600px">
      <div id="carouselExampleAutoplaying1" class="carousel slide" data-bs-ride="carousel" data-ride="carousel" data-interval="5000">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "how_to_image11.jpg", height: 440, width: 1143, class: "d-block w-100" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "how_to_image2.jpg", height: 440, width: 1143, class: "d-block w-100" %>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying1" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying1" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class="card-body">
        <p class="card-text" style="font-weight: 700; font-size: 25px;">新しくヒヤリハットや報告を投稿する方法</p>
        <p class="card-text">①　画像の一番上にある新規投稿の文字をクリックします<br>
                             ②　画面中央にある入力欄に文字を入力します（灰色の画像を選択ボタンをクリックすると画像を任意で投稿できます）<br>
                             ③　文字を入力し終わって青い送信ボタンを押すと投稿完了です</p>
      </div>
    </div>
  </div>
</div>
<div class="container d-flex justify-content-center align-items-center" style="margin-top: 30px;">
  <div class="container">
    <div class="card" style="width: 80vw; height: 600px">
      <div id="carouselExampleAutoplaying2" class="carousel slide" data-bs-ride="carousel" data-ride="carousel" data-interval="5000">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "how_to_image11.jpg", height: 440, width: 1143, class: "d-block w-100" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "how_to_image4.jpg", height: 440, width: 1143, class: "d-block w-100" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "how_to_image3.jpg", height: 440, width: 1143, class: "d-block w-100" %>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying2" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying2" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class="card-body">
        <p class="card-text" style="font-weight: 700; font-size: 23px;">投稿に対してコメントする方法</p>
        <p class="card-text">①　画像のように投稿内容に灰色の詳細ボタンがあるのでクリックします<br>
                             ②　いいねと意見の詳細ボタンが現れるので意見の詳細ボタンをクリックします<br>
                             ③　画像内の右側のようにコメントを入力できる欄があるので文字を入力します<br>
                             ④　文字を入力し終わって青い送信ボタンをクリックするとコメント投稿完了です</p>
      </div>
    </div>
  </div>
</div>
<div class="container d-flex justify-content-center align-items-center" style="margin-top: 30px; margin-bottom: 30px;">
  <div class="container">
    <div class="card" style="width: 80vw; height: 600px">
      <div id="carouselExampleAutoplaying3" class="carousel slide" data-bs-ride="carousel" data-ride="carousel" data-interval="5000">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= image_tag "how_to_image11.jpg", height: 440, width: 1143, class: "d-block w-100" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "how_to_image5.jpg", height: 440, width: 1143, class: "d-block w-100" %>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying3" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying3" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class="card-body">
        <p class="card-text" style="font-weight: 700; font-size: 25px;">投稿に対していいねする方法</p>
        <p class="card-text">①　画像のように投稿内容に灰色の詳細ボタンがあるのでクリックします<br>
                             ②　いいねと意見の詳細ボタンが現れるので<span style="font-weight: 700; color: #DC3444;">いいね</span>ボタンをクリックします<br>
                             ③　クリックしたらいいね完了です。投稿内容の一番下に表示されているいいね数が増えていいねの数が可視化されます</p>
      </div>
    </div>
  </div>
</div>

app/views/opinions/index.html.erb
<%= render partial: "header" %>  
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @opinions.each do |opinion| %>
      <div class="col">
        <div class="card h-100">
          <%= image_tag (opinion.image) if opinion.image.attached? %>
          <div class="card-body">
            <h3 class="card-title text-center"><%= opinion.title %></h5>
            <p class="card-text text-center"><%= opinion.text %></p>
            <div class="btn-group">
              <button class="btn btn-secondary btn-sm dropdown-toggle btn-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                詳細
              </button>
              <ul class="dropdown-menu">
                <div class="text-center m-2">
                  <li>
                    <div id="like-btn<%= opinion.id %>">
                        <%= turbo_frame_tag dom_id(opinion, :like) do %>
                          <% if user_signed_in? && opinion.liked_by?(current_user)%>
                            <%=link_to "いいね済", opinion_likes_path(opinion.id), data: { turbo_method: :delete }, class: "btn btn-danger", style: "text-decoration: none;", placeholder: "いいね済" %>
                          <% else %>
                            <%=link_to "いいね", opinion_likes_path(opinion.id), data: { turbo_method: :post }, class: "btn btn-outline-danger", style: "text-decoration: none;", placeholder: "いいね" %>
                          <% end %>
                        <% end %>
                    </div>
                  </li>
                </div>
                <div class="text-center m-3">
                  <li>
                    <%= link_to "意見の詳細", opinion_path(opinion.id), class: "btn btn-secondary" %>
                  </li>
                </div>
              </ul>

            </div>
          </div>
          <div class="card-footer d-flex">
            <small class="text-body-secondary"><%= l opinion.created_at %></small>
            <h5 style="margin-left: 15px;">いいね数:</h5><%= opinion.likes.count %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "refresh" %>

app/views/opinions/new.html.erb
<%= render partial: "header" %>
<div class="container d-flex justify-content-center align-items-center" style="min-height: 70vh;">
  <div class="card" style="min-width: 40vw;">
    <div class="card-body">
      <h2 class="text-center">新規投稿</h2>
        <%= form_with(model: @opinion, data: { turbo: false }, local: true) do |f| %>
        <%= render "shared/error_messages", model: f.object %>
        <div class="mb-3 text-center">
          <%= f.label :image, class: "btn btn-secondary btn-sm" do %>
             画像を選択
            <%= f.file_field :image, style: "display: none;" %>
          <% end %>
        </div>
        <div class="mb-3 text-center">
          <%= f.text_area :title, placeholder:"タイトルを入力", class: "w-75" %>
        </div>
        <div class="mb-3 text-center">
          <%= f.text_area :text, placeholder:"本文を入力", class: "w-75" %>
        </div>
        <div class="text-center">
          <%= f.submit "送信", class: "btn btn-primary" %>
        </div>
        <% end %>
    </div>
  </div>
</div>

app/views/opinions/search.html.erb
<%= render partial: "header" %>
<div class="d-flex justify-content-center">
  <div class="mb-3 w-25">
    <%= form_with(url: search_opinions_path, local: true, method: :get, class: "search-form") do |form| %>
      <div class="input-group">
        <span class="input-group-text"><i class="bi bi-search"></i></span>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "form-control search-input" %>
        <button type="submit" class="btn btn-primary">検索</button>
      </div>
    <% end %> 
  </div>
</div>
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @opinions.each do |opinion| %>
      <div class="col">
        <div class="card h-100">
          <%= image_tag (opinion.image) if opinion.image.attached? %>
          <div class="card-body">
            <h3 class="card-title text-center"><%= opinion.title %></h5>
            <p class="card-text text-center"><%= opinion.text %></p>
            <div class="btn-group">
              <button class="btn btn-secondary btn-sm dropdown-toggle btn-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                詳細
              </button>
              <ul class="dropdown-menu">
                <div class="text-center">
                  <li><a class="dropdown-item" href="#"><p class="card-text"><div id="like-btn<%= opinion.id %>"><%= render partial: "likes/like", locals: { opinion: opinion } %></div></a></li>
                </div>
                <div class="text-center">
                  <li><a class="dropdown-item" href="#"><p class="card-text"><%= link_to "意見の詳細", opinion_path(opinion.id) %></p></a></li>
                </div>
              </ul>
            </div>
          </div>
          <div class="card-footer">
            <small class="text-body-secondary"><%= l opinion.created_at %></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/opinions/show.html.erb
<%= render partial: "header" %>
<div class="container d-flex justify-content-center align-items-center">
  <div class="card my-3 w-50">
    <div class="card-body text-center">
      <h5 class="card-title"><%= @opinion.title %></h5>
      <p class="card-text"><%= @opinion.text %></p>
      <p class="card-text"><%= @opinion.created_at %></p>
      <div class="image-tag">
        <%= image_tag(@opinion.image.variant(resize: '500x500')) if @opinion.image.attached? %>
      </div>
    </div>
  </div>
  <div class="container w-50 text-center">
    <h4>＜コメント一覧＞</h4>
    <% if user_signed_in? %>
      <%= form_with(model: [@opinion, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2", class: "form-control" %>
        <%= form.submit "送信", class: "btn btn-primary mt-4 mb-4" %>
      <% end %>
    <% else %>
      <p>＊＊＊ コメント投稿には新規登録/ログインが必要です ＊＊＊</p>
    <% end %>
    <ul class="list-group d-flex justify-content-center">
      <% @comments.each do |comment| %>
      <li class="list-group-item w-50 text-center"><%= comment.text %></li>
      <% end %>
    </ul>
  </div>
</div>